### ISSUE TITLE
h264 playback stutters

### ISSUE THREAD

**Issue by tinywrkb** [flathub/org.qutebrowser.qutebrowser#24]

**Comment by tidux** [comment]
It's not actually H.264, it's falling back to other codecs.  It looks stuttery on YouTube because the adaptive bitrate/codec playback is breaking.  Launch with `flatpak run`, go to https://lab.html5test.com/codecs/ , and see that H.264 isn't supported, while on stderr you see the application looking for ffmpeg.

**Comment by tinywrkb** [comment]
I added the extension and it working as expected on my system.  
The changes are already merged so you should get an update soon via Flathub.  
You can also install the test build.

> Build [43470 successful](https://flathub.org/builds/#/builders/32/builds/43470)
> To test this build, install it from the testing repository:
> 
> ```
> flatpak install --user https://dl.flathub.org/build-repo/41824/org.qutebrowser.qutebrowser.flatpakref
> ```

I'm keeping this issue open for now, let me know if something is still broken.

**Comment by tidux** [comment]
Yup, test works on http://www.html5videoplayer.net/html5video/mp4-h-264-video-test/ .  Thanks!  Feel free to close when published to flathub.

**Comment by tinywrkb** [comment]
@tidux thanks for the feedback.

**Comment by tinywrkb** [comment]
It's now in Flathub, closing.
